[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
actix-web = "4"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
reqwest = "0.11"
